// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9KfYTmEtEdz743lqKOh5D4Mau-tJar50',
    appId: '1:418265530629:web:a9e8327712562f1372376c',
    messagingSenderId: '418265530629',
    projectId: 'ridetrack-a18f6',
    authDomain: 'ridetrack-a18f6.firebaseapp.com',
    storageBucket: 'ridetrack-a18f6.appspot.com',
    measurementId: 'G-HM977VRFJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATt6lhlzYPoFqv9b5k-LFyhhIKTPyU6qQ',
    appId: '1:418265530629:android:0843a6111910c4a472376c',
    messagingSenderId: '418265530629',
    projectId: 'ridetrack-a18f6',
    storageBucket: 'ridetrack-a18f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz4ay5su9TUuvgj_HCjZL_r9Du-A1Lmvs',
    appId: '1:418265530629:ios:e5d4a070e6d56bc772376c',
    messagingSenderId: '418265530629',
    projectId: 'ridetrack-a18f6',
    storageBucket: 'ridetrack-a18f6.appspot.com',
    iosBundleId: 'com.example.bikeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz4ay5su9TUuvgj_HCjZL_r9Du-A1Lmvs',
    appId: '1:418265530629:ios:e5d4a070e6d56bc772376c',
    messagingSenderId: '418265530629',
    projectId: 'ridetrack-a18f6',
    storageBucket: 'ridetrack-a18f6.appspot.com',
    iosBundleId: 'com.example.bikeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9KfYTmEtEdz743lqKOh5D4Mau-tJar50',
    appId: '1:418265530629:web:39d115de585601f172376c',
    messagingSenderId: '418265530629',
    projectId: 'ridetrack-a18f6',
    authDomain: 'ridetrack-a18f6.firebaseapp.com',
    storageBucket: 'ridetrack-a18f6.appspot.com',
    measurementId: 'G-609GQ1Y458',
  );
}
